trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    pip install databricks-cli
  displayName: "Install Databricks CLI"

- script: |
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)
    EOF
  displayName: "Authenticate Databricks"

- script: |
    databricks bundle deploy
  displayName: "Deploy DAB"

- script: |
    databricks bundle run healthcare_pipeline
  displayName: "Run Healthcare Pipeline"